#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=64
#SBATCH --mem-per-cpu=3500MB
#SBATCH --time=120:00:00
#SBATCH --partition=sla-prio
#SBATCH --qos=burst4x
#SBATCH --account=ixd4_n_bc
#SBATCH --output=vasp.out
#SBATCH --error=vasp.err
#SBATCH --job-name=MgO

export UCX_TLS=all

cd $SLURM_SUBMIT_DIR
module purge
module use /storage/icds/RISE/sw8/modules/
module load vasp/vasp-6.4.1v

eval "$(conda shell.bash hook)"
conda activate research

python cstdn.py